version: '3.8'

services:
  node1:
    build: .
    hostname: node1
    ports:
      - "5001:5000"
    environment:
      - NODE_ID=node1
    # Changed 'flask run' to 'python app.py' for more reliable startup
    command: python app.py

  node2:
    build: .
    hostname: node2
    ports:
      - "5002:5000"
    environment:
      - NODE_ID=node2
    # Changed 'flask run' to 'python app.py' for more reliable startup
    command: python app.py

  node3:
    build: .
    hostname: node3
    ports:
      - "5004:5000"
    environment:
      - NODE_ID=node3
    # Changed 'flask run' to 'python app.py' for more reliable startup
    command: python app.py